// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_laoyout from "./routes/_laoyout.tsx";
import * as $consts from "./routes/consts.ts";
import * as $index from "./routes/index.tsx";
import * as $posts_slug_ from "./routes/posts/[slug].tsx";
import * as $posts_index from "./routes/posts/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_laoyout.tsx": $_laoyout,
    "./routes/consts.ts": $consts,
    "./routes/index.tsx": $index,
    "./routes/posts/[slug].tsx": $posts_slug_,
    "./routes/posts/index.tsx": $posts_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
